version: "3.9"

services:
  frontend:
    build:
      context: ./src/frontend
    volumes:
      - type: bind
        source: ./src/frontend/src
        target: /app/src
        read_only: true
    ports:
      - "3000:3000"

  master:
    build:
      context: ./src/master
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.master
    environment:
      PYTHONUNBUFFERED: no
    volumes:
      - type: bind
        source: ./src/master
        target: /app
        read_only: true
    command:
      - --reload
  db:
    image: postgres:12
    env_file:
      - .env.master
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  migrations:
    image: djb/migrations
    build:
      context: src/api
      dockerfile: Dockerfile-migrations
    restart: 'no'
    env_file:
      - .env.master

  api:
    image: djb/api
    build:
      context: src/api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - .env.master
    volumes:
      - type: bind
        source: ./src/api/djb_api
        target: /app/djb_api
        read_only: true

volumes:
  db:
